name: Get m3u8
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install yt-dlp
      run: |
        md D:\a\me\me\hello
        dir
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe -o D:\a\me\me\hello\yt-dlp.exe
        dir
    - name: Get abcnewsau.m3u8
      run: |
        D:\a\stbernie2020\me\hello\yt-dlp.exe -g -f 95 https://www.youtube.com/c/NewsOnABC/live > D:\a\me\me\hello\abcnewsau.m3u8
        dir
        type D:\a\me\me\hello\abcnewsau.m3u8
    - name: Get indosiar.m3u8
      run: |
        D:\a\me\me\hello\yt-dlp.exe  -g http://vidio.com/live/205-indosiar > D:\a\me\me\hello\indosiar.m3u8
         dir
