name: epg
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download epg
      run : |
      
        wget https://www.bevy.be/generate/7Z1l92Ma0H.xml      
      
        git config --global user.name "actions"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "Update master"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push
