name: Get m3u8
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp
    - name: Get abcnewsau.m3u8
      run: |
        touch ./abcnewsau.m3u8
        sudo cat >./abcnewsau.m3u8 <<EOL
        $(yt-dlp -g -f 95 https://www.youtube.com/c/NewsOnABC/live)
        EOL
    - name: Get abcnewsus.m3u8
      run: |
        touch ./abcnewsus.m3u8
        sudo cat >./abcnewsus.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 95 https://www.youtube.com/@ABCNews/live)
        EOL
    - name: Get aljazeera.m3u8
      run: |
        touch ./aljazeera.m3u8
        sudo cat >./aljazeera.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 95 https://www.youtube.com/@AlJazeeraEnglish/live)
        EOL
    - name: Get antv.m3u8
      run: |
        touch ./antv.m3u8
        sudo cat >./antv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 720p https://www.vidio.com/live/782-antv)
        EOL
    - name: Get arirangtv.m3u8
      run: |
        touch ./arirangtv.m3u8
        sudo cat >./arirangtv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 95 https://www.youtube.com/@KOREAarirangTV/live)
        EOL
    - name: Get asot.m3u8
      run: |
        touch ./asot.m3u8
        sudo cat >./asot.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 95 https://www.youtube.com/@astateoftrance/live)
        EOL
    - name: Get btv.m3u8
      run: |
        touch ./btv.m3u8
        sudo cat >./btv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 720p https://www.vidio.com/live/6165-btv)
        EOL
    - name: Get dwnews.m3u8
      run: |
        touch ./dwnews.m3u8
        sudo cat >./dwnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 94 https://www.youtube.com/@dwnews/live)
        EOL
    - name: Get france24.m3u8
      run: |
        touch ./france24.m3u8
        sudo cat >./france24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 95 https://www.youtube.com/@France24_en/live)
        EOL
    - name: Get goodlife.m3u8
      run: |
        touch ./goodlife.m3u8
        sudo cat >./goodlife.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/@TheGoodLiferadio/live)
        EOL
    - name: Get i24.m3u8
      run: |
        touch ./i24.m3u8
        sudo cat >./i24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -vU -g https://www.youtube.com/@i24NEWS_EN/live)
        EOL        
    - name: Get idol.m3u8
      run: |
        touch ./idol.m3u8
        sudo cat >./idol.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 480p http://twitch.tv/nihonongakukaitv)
        EOL
    - name: Get indiatoday.m3u8
      run: |
        touch ./indiatoday.m3u8
        sudo cat >./indiatoday.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 95 https://www.youtube.com/@indiatoday/live)
        EOL
    - name: Get jpopsong.m3u8
      run: |
        touch ./jpopsong.m3u8
        sudo cat >./jpopsong.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 94 https://www.youtube.com/@JPOP-Collection/live)
        EOL
    - name: Get kompastv.m3u8
      run: |
        touch ./kompastv.m3u8
        sudo cat >./kompastv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 95 https://www.youtube.com/@kompastv/live)
        EOL
    - name: Get kpop.m3u8
      run: |
        touch ./kpop.m3u8
        sudo cat >./kpop.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/@TheKPOP/live)
        EOL
    - name: Get mafi2a.m3u8
      run: |
        touch ./mafi2a.m3u8
        sudo cat >./mafi2a.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp -g https://ok.ru/video/4403826925204)
        EOL
    - name: Get mentaritv.m3u8
      run: |
        touch ./mentaritv.m3u8
        sudo cat >./mentaritv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 720p https://www.vidio.com/live/8237-mentari-tv)
        EOL
    - name: Get metrotv.m3u8
      run: |
        touch ./metrotv.m3u8
        sudo cat >./metrotv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 94 https://www.youtube.com/@metrotvnews/live)
        EOL
    - name: Get ncs1.m3u8
      run: |
        touch ./ncs1.m3u8
        sudo cat >./ncs1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 94 https://www.youtube.com/@NCSArcade/live)
        EOL
    - name: Get radiometal.m3u8
      run: |
        touch ./radiometal.m3u8
        sudo cat >./radiometal.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f hls-2 https://vk.com/video-12357723_456239136)
        EOL
    - name: Get ritsatv.m3u8
      run: |
        touch ./ritsatv.m3u8
        sudo cat >./ritsatv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://ok.ru/live/6236642418231)
        EOL
    - name: Get sctv.m3u8
      run: |
        touch ./sctv.m3u8
        sudo cat >./sctv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -f 720p-1 -g https://www.vidio.com/live/204-sctv)
        EOL
    - name: Get trtworld.m3u8
      run: |
        touch ./trtworld.m3u8
        sudo cat >./trtworld.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 95 https://www.youtube.com/@trtworld/live)
        EOL
    - name: Get tvone.m3u8
      run: |
        touch ./tvone.m3u8
        sudo cat >./tvone.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 95 https://www.youtube.com/@tvOneNews/live)
        EOL
    - name: Get unitednations.m3u8
      run: |
        touch ./unitednations.m3u8
        sudo cat >./unitednations.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp -g -f 95 https://www.youtube.com/@unitednations/live)
        EOL

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: YTlive m3u8
        path: .
    - name: Git push assets to "YTlive" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b YTlive
        git add .
        git commit -m "Update YTlive"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin YTlive
